image: node:11

lint:
  script:
    - npm install
    - npm test

pages:
  script:
    - npm install
    - npm run build
    - mv dist/ public
  after_script:
  - npm run deploy
  artifacts:
    paths:
    - public
  only:
  - master
