image: node:24

lint:
  script:
    - npm install
    - npm run build
    - npm test

pages:
  script:
    - npm ci
    - npm run build
    - mv _site/ public
  after_script:
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - tags
